### ISSUE TITLE
Create NIH Search RFI response

### ISSUE THREAD

**Issue by NoopDog** [NIH-NCPI/ncpi-search-activities#11]
https://datascience.nih.gov/search-capabilities-across-the-biomedical-landscape

NIH requests input on use cases, expectations, and capabilities for enabling data and information discovery (search) to enhance NIH-wide data discovery and its reuse. In particular, NIH would like to understand better researchers’ experiences and expectations in finding data and information that would greatly enable their research capabilities and uncover underlying barriers or opportunities that can move the search landscape forward. Building on prior efforts, NIH seeks to identify how production level capabilities can be provided for search, assuming that such plans are realistic from the point of view of data submitters as they fulfill the requirements of the recently issued NIH Policy for Data Management and Sharing (DMS Policy). The information gathered from this RFI is intended to inform and frame the discussions for an NIH supported workshop in January 2022.  Invitations may be drawn from the larger research community, including responders to this RFI.

**Comment by linikujp** [comment]
It is completed.
